plugins {
    id "com.android.application"
}

def romanVoiceVersion = new Properties()
file("../version.properties").withInputStream { romanVoiceVersion.load(it) }

android {
    namespace "app.romanvoice.ime"
    compileSdk romanVoiceVersion.getProperty("compileSdk").toInteger()
    buildToolsVersion romanVoiceVersion.getProperty("buildToolsVersion")

    defaultConfig {
        applicationId "app.romanvoice.ime"
        minSdk romanVoiceVersion.getProperty("minSdk").toInteger()
        targetSdk romanVoiceVersion.getProperty("targetSdk").toInteger()
        versionCode romanVoiceVersion.getProperty("versionCode").toInteger()
        versionName romanVoiceVersion.getProperty("versionName")
    }

    buildTypes {
        debug {
            versionNameSuffix "-debug"
        }
    }
}
